apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-service
  namespace: solidarytech
  labels:
    app: volunteer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: volunteer-service
  template:
    metadata:
      labels:
        app: volunteer-service
    spec:
      containers:
        - name: volunteer-service
          image: volunteer-service-image
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: volunteer-service-config
          resources:
            requests:
              cpu: 50m
              memory: 80Mi
            limits:
              cpu: 300m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 5
