apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solidarytech
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml
images:
- name: volunteer-service-image
  newName: 908212073039.dkr.ecr.us-east-1.amazonaws.com/volunteer-service
  newTag: a555b482d45ee5d79cf052d8a6a6f2bc548e5ffa
