apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solidarytech
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml
images:
- name: volunteer-service-image
  newName: 908212073039.dkr.ecr.us-east-1.amazonaws.com/volunteer-service
  newTag: 4472bc2734526d7d48eef490a14c41f0a4af3bc6
