apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: donation-service
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/leobezuti/postech-fase-5-gitops.git
    targetRevision: main
    path: donation-service
  destination:
    server: https://kubernetes.default.svc
    namespace: solidarytech
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
