apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solidarytech
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml
images:
- name: ngo-service-image
  newName: 908212073039.dkr.ecr.us-east-1.amazonaws.com/ngo-service
  newTag: 44c0743d3b9a02c03371d90c801f482411774122
