apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solidarytech
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
images:
- name: ngo-service-image
  newName: 510818802086.dkr.ecr.us-east-1.amazonaws.com/ngo-service
  newTag: f5874280ab21a18c50063619c5387ebaa2944f00
