apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solidarytech
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- ingress.yaml
images:
- name: ngo-service-image
  newName: 908212073039.dkr.ecr.us-east-1.amazonaws.com/ngo-service
  newTag: f6891eb0d9b4461c5585b8c7d759b2427248cfd5
